image: angulardeploy

variables:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8

stages:
#    - unitTests #TODO, Not implemented yet
#    - integrationTests #TODO, Not implemented yet
    - buildAngular
    - editVersion
    - deployAngular

before_script:
    # Get version.
    # Variable CI_COMMIT_TAG is set only when tag was pushed.
    - export VERSION=$(if [[ "$CI_COMMIT_TAG" == "" ]]; then echo $(dpkg-parsechangelog --show-field version); else echo $CI_COMMIT_TAG | cut -c 2-; fi)
    - echo $VERSION
    # Install Angular dependencies

#TODO, not implemented yet
#unitTests:
#    stage: unitTests
#    script:
#        - ng test --browsers ChromeHeadless
#    only:
#        - triggers
#        - branches
#        - tags

#TODO, not implemented yet
#integrationTests:
#    stage: integrationTests
#    script:
#        - ng e2e
#    only:
#        - triggers
#        - branches
#        - tags

buildAngular:
    stage: buildAngular
    script:
        - cp /usr/local/npmrc ~/.npmrc
        - npm install
        - ng build --configuration=production
    only:
        - triggers
        - branches
        - tags
    artifacts:
      paths:
        - ./dist
      expire_in: 1 hour

editVersion:
    stage: editVersion
    script:
        - export GIT_SSH_COMMAND='ssh -i ~/.ssh/kyposervicekey'
        - ssh -o "StrictHostKeyChecking no" git@gitlab.ics.muni.cz && sleep 1
        - git clone git@gitlab.ics.muni.cz:kypo2/frontend-new/kypo2-angular-topology.git
        - cd $CI_PROJECT_NAME
        - git config --global user.name "KYPO CI" && git config --global user.email "kyposervice@ics.muni.cz"
        # sed -i -e 's/  "version":.*/  "version": "'$VERSION'",/' projects/user-and-group-management/package.json'
        # The command above is not a friend with YAML. Run it in a script as a workaround.
        - bash /usr/local/changeVersion.sh $VERSION kypo2-topology-graph
        - git commit -am "Update project package.json version based on GitLab tag. Done by CI" && sleep 1
        - git push
    only:
        - tags

deployAngular:
    stage: deployAngular
    script:
        - git checkout master && git pull
        - cp /usr/local/npmrc ~/.npmrc
        - 'npm run generate-package && cd dist/kypo2-topology-graph &&  npm publish --registry=http://kypo-storage.ics.muni.cz:8081/repository/npm-hosted'
    only:
        - tags
